server:
  port: 8061
  
spring:
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${JDBC_CONNECTION_STRING}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8060

  mail:
    host: smtp.office365.com
    username: temp2710@outlook.com
    password: Temp@2710
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  threads:
    virtual:
      enabled: true
app:
  timezone: IST
  auth-cred: sathish_ch:S@th!$h
  url: http://localhost:8060/oauth2/token
  passwordlink-expiry: 24
  otp-expiry: 5
  isOtpEnable: true
  aes-key: U2F0aGlzaEt1bWFyQ2gyNw==