server:
  port: 8061
  forward-headers-strategy: framework
  max-http-request-header-size: 200000000
  tomcat:
    max-http-form-post-size: 200000000
    max-swallow-size: 200000000

spring:
  application:
    name: skch-api-server
  datasource:
    url: ${JDBC_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000 # 5 seconds
      leak-detection-threshold: 200000 # 200 seconds (approx 3.33 minutes)
      pool-name: SpringBootHikariCP
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8060
#          jwk-set-uri: http://localhost:8060/.well-known/jwks.json

  mail:
    host: smtp.office365.com #smtp.gmail.com
    username: skch@outlook.com
    password: mypass
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      
app:
  timezone: "Asia/Kolkata"
  auth-cred: sathish_ch:S@th!$h
  url: http://localhost:8060/oauth2/token
  passwordlink-expiry: 24
  otp-expiry: 5
  isOtpEnable: false
  aes-key: U2F0aGlzaEt1bWFyQ2gyNw==
  batch-size: 1000

smarty:
  auth-id: ${SMARTY_AUTH_ID}
  auth-token: ${SMARTY_AUTH_TOKEN}
  batch-size: 100

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      apache:
#        catalina: DEBUG
#logging:
#  level:
#    web: DEBUG
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE
#      springframework: DEBUG
#        security: DEBUG
#        cache: DEBUG
#        aop: DEBUG

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: '*' #openapi, swagger-ui, health
  endpoint:
    health:
      show-details: always
