server:
  port: 8062
  forward-headers-strategy: framework
  max-http-request-header-size: 128KB
  tomcat:
    max-http-form-post-size: 128KB
    max-swallow-size: 128KB

spring:
  application:
    name: skch-api-server
  datasource:
    url: ${JDBC_CONNECTION_STRING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
      validation-timeout: 5000 # 5 seconds
      leak-detection-threshold: 200000 # 200 seconds (approx 3.33 minutes)
      pool-name: SpringBootHikariCP
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_SERVICE_ENDPOINT}
#          jwk-set-uri: http://localhost:8060/.well-known/jwks.json

  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST} #localhost # use "redis" if Spring Boot is dockerized
      port: ${REDIS_PORT} #6379
      password: ${REDIS_PASSWORD} #Redis@123
      timeout: 2000
      ssl:
        enabled: ${REDIS_SSL_ENABLED} #false

app:
  timezone: "Asia/Kolkata"
  auth-cred: ${OAUTH_CLIENT_ID}:${OAUTH_CLIENT_SECRET}
  url: ${OAUTH_SERVICE_ENDPOINT}/oauth2/token
  passwordlink-expiry: 24
  otp-expiry: 5
  isOtpEnable: false
  aes-key: ${AES_KEY}
  batch-size: 1000
  request-verify-token: SpringBootReactRequestDevelopment
  token-expiry: 20

auth:
  server:
    authorize-url: ${OAUTH_SERVICE_ENDPOINT}/oauth2/authorize
    token-url: ${OAUTH_SERVICE_ENDPOINT}/oauth2/token
    revoke-url: ${OAUTH_SERVICE_ENDPOINT}/oauth2/revoke
  client-id: ${OAUTH_CLIENT_ID}
  client-secret: ${OAUTH_CLIENT_SECRET}
  redirect-uri: http://localhost:8060/apiService/authenticate/callback
  scope: read

cors:  
  cors-origin:
    - http://localhost:5173
    - http://localhost:4173

smarty:
  auth-id: ${SMARTY_AUTH_ID}
  auth-token: ${SMARTY_AUTH_TOKEN}
  batch-size: 100

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      apache:
#        catalina: DEBUG
#logging:
#  level:
#    web: DEBUG
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE
#      springframework: DEBUG
#        security: DEBUG
#        cache: DEBUG
#        aop: DEBUG

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true
  show-actuator: false
  remove-broken-reference-definitions: true

management:
  endpoints:
    web:
      exposure:
        include: '*' #openapi, swagger-ui, health
  endpoint:
    health:
      show-details: always
